# Generated by Django 3.1.5 on 2021-01-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countryapp', '0002_remove_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
    ]
